### ISSUE TITLE
Files da caricare

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/comuni-italiani#1]
### CSV
- [x] stemmi_comuni_italiani.csv
- [x] email_comuni_italiani.csv
- [x] anagrafica_comuni_italiani.csv (questo nome è adatto? mi riferisco al mio [csv preferito](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/dati-popolazione/elenco-comuni-italiani.csv) preparato da @gabacode )
- [x] realizzare README.md per ogni file con descrizione e schema dati

### IMG
- [x] stemmi

**Comment by dennisangemi** [comment]
Forse conviene fondere tutti i csv sopra elencati per crearne uno unico?

**Comment by gbvitrano** [comment]
buona idea 👍
