### ISSUE TITLE
Aggiungere fonti

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/comuni-italiani#10]
Dove? Nel readme princpale o nel readme della cartella `dati` ?

**Comment by gbvitrano** [comment]
nel mio file i dati vengono da queste fonti:
Amministrazioni: [indicepa.gov.it](https://indicepa.gov.it/ipa-dati/dataset/amministrazioni)
Popolazione: [Istat](https://www.istat.it/)
Stemmi: [araldicacivica.it](https://www.araldicacivica.it/) e [Wikipedia Italia](https://it.wikipedia.org/wiki/Pagina_principale/)

**Comment by pigreco** [comment]
> Dove? Nel readme princpale o nel readme della cartella `dati` ?

secondo me nel readme cartella dati

grazie @dennisangemi

**Comment by gbvitrano** [comment]
oltre al metodo di [Totò](https://github.com/opendatasicilia/comuni-italiani/issues/11#issuecomment-928958397) per estrarre i dati istat gli stessi possono essere scaricati da [qui](http://demo.istat.it/index.php) [demo.istat.it ](http://demo.istat.it/index.php) per i meno smanettoni :-)

**Comment by pigreco** [comment]
> oltre al metodo di [Totò](https://github.com/opendatasicilia/comuni-italiani/issues/11#issuecomment-928958397) per estrarre i dati istat gli stessi possono essere scaricati da [qui](http://demo.istat.it/index.php), [demo.istat.it ](http://demo.istat.it/index.php) per i meno smanettoni :-)

i dati sulla popolazione sono uguali?

**Comment by gbvitrano** [comment]
> > oltre al metodo di [Totò](https://github.com/opendatasicilia/comuni-italiani/issues/11#issuecomment-928958397) per estrarre i dati istat gli stessi possono essere scaricati da [qui](http://demo.istat.it/index.php), [demo.istat.it ](http://demo.istat.it/index.php) per i meno smanettoni :-)
> 
> i dati sulla popolazione sono uguali?

in quelli su demo istat ci sono anche maschi/femmine e tante altre colonne

**Comment by dennisangemi** [comment]
Chiudo perchè sono state aggiunte [qui ](https://github.com/opendatasicilia/comuni-italiani/tree/main/dati#fonti)
