### ISSUE TITLE
SPARQL query wikidata comuni italiani

### ISSUE THREAD

**Issue by gpirrotta** [opendatasicilia/comuni-italiani#13]
Ciao cari,
ho aggiunto il [dataset](https://raw.githubusercontent.com/opendatasicilia/comuni-italiani/main/dati/wikidata.csv) Wikidata dei comuni italiani.

Questa issue solo per ricordarmi la query SPARQL da invocare per aggiornare i dati.
```
SELECT ?pro_com_t ?wikidata
WHERE {
?wikidata wdt:P31  wd:Q747074;
          wdt:P635 ?pro_com_t.   
}
```
[SPARQL query](https://query.wikidata.org/#SELECT%20%3Fpro_com_t%20%3Fwikidata%0AWHERE%20%7B%0A%3Fwikidata%20wdt%3AP31%20%20wd%3AQ747074%3B%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP635%20%3Fpro_com_t.%20%20%20%0A%7D)
[Output](https://w.wiki/4LMV)

Oppure direttamente da riga di comando:

`curl -X POST https://query.wikidata.org/sparql --data-urlencode 'query=SELECT ?pro_com_t ?wikidata { ?wikidata wdt:P31  wd:Q747074;  wdt:P635 ?pro_com_t. }' -H 'Accept:text/csv' > ./wikidata.csv`

Bye

**Comment by dennisangemi** [comment]
Grazie mille Giovanni ;)

**Comment by gpirrotta** [comment]
Aggiunto download da riga di comando.
bye

**Comment by aborruso** [comment]
> Aggiunto download da riga di comando.

Love love and love
