### ISSUE TITLE
Schema dati da correggere

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/comuni-italiani#14]
Ciao @dennisangemi ,
non so sei stato tu a compilare gli schemi di sotto. Volevo sottolineare che i campi che contengono i codici comunali Istat da 6 caratteri, non sono numerici, ma sono di testo.

![image](https://user-images.githubusercontent.com/30607/140417471-9da42ef7-e918-49b4-a2c0-dba3bdf95fcf.png)

**Comment by pigreco** [comment]
Buongiorno, aggiungo che in `pro_com_t`, la `t` finale sta proprio per `testo`; mentre la `pro_com` è numerico.

grazie per l'ottimo lavoro

**Comment by dennisangemi** [comment]
Buongiorno, sorry per l'errore e grazie per avermelo fatto notare. Provvedo a rettificare
