### ISSUE TITLE
Aggiunto dataset ISTAT popolazione residente con classi età ">=12" e "<12"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/comuni-italiani#16]
Fonte: http://demo.istat.it/pop2021/dati/comuni.zip

```bash
# scarica dati
curl -kL "http://demo.istat.it/pop2021/dati/comuni.zip" >./comuni.zip"

# ristruttura il file
zcat ./comuni.zip | tail -n +2 |  \
mlr --csv put '${Codice comune}=fmtnum(${Codice comune},"%06d");$Totale=${Totale Maschi}+${Totale Femmine};if (${Età}>=12){$fascia=">=12"}else{$fascia="<12"}' \
then filter -x -S '${Età}=="999"' \
then stats1 -a sum -f Totale -g "Codice comune",fascia \
then reshape -s fascia,Totale_sum then put '$totale=${<12}+${>=12}' \
then rename "Codice comune",pro_com_t >./ISTAT_popolazione_2021.csv
```

- output https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/ISTAT_popolazione_2021.csv
- descrizione https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/README.md#istat_popolazione_2021csv

**Comment by pigreco** [comment]
Buongiorno, ma questo script è oro che cola

Qui serve una ricetta da mettere su T'ansignari :-)

**Comment by aborruso** [comment]
> Buongiorno, ma questo script è oro che cola

Grazie. Ho aggiunto anche requisiti
