### ISSUE TITLE
Aggiornare target

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/comuni-italiani#17]
La popolazione vaccinabile è cambiata quindi conviene aggiornare il file [`ISTAT_popolazione_2021.csv`](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/ISTAT_popolazione_2021.csv). Rifletterei anche sull'eventualità di scegliere un nome più appropriato

Sarebbe possibile riutilizzare questo script https://github.com/opendatasicilia/comuni-italiani/issues/16 (Grazie @aborruso )

**Comment by pigreco** [comment]
lo script dovrebbe essere:

```bash
### requisiti ###
# miller, che si installa con "apt-get install miller"
# zcat, che si installa con "apt-get install gzip"
### requisiti ###

# scarica dati
curl -kL "http://demo.istat.it/pop2021/dati/comuni.zip" >./comuni.zip

# ristruttura il file
zcat ./comuni.zip | \
tail -n +2 | \
mlr --csv put '${Codice comune}=fmtnum(${Codice comune},"%06d");$Totale=${Totale Maschi}+${Totale Femmine};if (${Età}>=5){$fascia=">=5"}else{$fascia="<5"}' \
then filter -x -S '${Età}=="999"' \
then stats1 -a sum -f Totale -g "Codice comune",fascia \
then reshape -s fascia,Totale_sum \
then put '$totale=${<5}+${>=5}' \
then rename "Codice comune",pro_com_t >./ISTAT_popolazione_2021.csv
```

**Comment by dennisangemi** [comment]
Grazie @pigreco e grazie @gabacode

**Comment by dennisangemi** [comment]
Secondo voi conviene:
- aggiornare e rinominare il file [`ISTAT_popolazione_2021.csv`](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/ISTAT_popolazione_2021.csv);
- creare un nuovo file `target.csv`

**Comment by pigreco** [comment]
> Secondo voi conviene:

purtroppo non capisco la domanda, forse mi manca qualcosa, oppure è troppo banale,
nella seconda ipotesi direi di aggiungere, al nome del file, `ISTAT_popolazione5_2021.csv` per far capire che il target è a partire dai 5 anni.

**Comment by dennisangemi** [comment]
Ciao @pigreco , io eviterei il nome del file così lungo (ISTAT_popolazione5_2021.csv); prova a dare un'occhiata agli altri file di questo repo: abbiamo provato a rendere tutto più sintetico e intuitivo possibile. Per questo proponevo di chiamarlo `target.csv`

**Comment by pigreco** [comment]
secondo me a breve cambia nuovamente il target, quindi si potrebbe chiamare `target5.csv`

**Comment by dennisangemi** [comment]
> secondo me a breve cambia nuovamente il target, quindi si potrebbe chiamare `target5.csv`

mi piace! grazie
