### ISSUE TITLE
Domanda sulla modalità di raccolta dei CAP

### ISSUE THREAD

**Issue by 8lall0** [opendatasicilia/comuni-italiani#19]
Salve,
volevo chiedere qual è il metodo usato per la raccolta dei diversi CAP italiani, visto che sono solitamente forniti in via privata previo pagamento dalle Poste.

Grazie!

**Comment by gbvitrano** [comment]
Ciao, i CAP sono stati estratti da questo file [amministrazioni.txt](https://indicepa.gov.it/ipa-dati/dataset/amministrazioni) dataset [Agid-iPA](https://indicepa.gov.it/ipa-dati/organization/agid-ipa) che trovi  [Opendata IPA](https://indicepa.gov.it/ipa-dati/)
Nei vari dataset trovi solo il codice e non i poligoni dei cap.

**Comment by 8lall0** [comment]
Grazie! Chiudo :)
