### ISSUE TITLE
Cancellare vecchia folder `stemmi_nomi_comuni`

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/comuni-italiani#2]
[Ridondante](https://github.com/opendatasicilia/comuni-italiani/tree/main/img/stemmi_nomi_comuni) in presenza dei files catalogati per codice ISTAT [qua](https://github.com/opendatasicilia/comuni-italiani/tree/main/img/stemmi_cod_istat).

Il [nuovo .csv](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/stemmi.csv) è molto piu' snello, secondo me potremmo fare anche a meno del nome del comune, e linkare tutto per `comune_codice_istat`

**Comment by dennisangemi** [comment]
> secondo me potremmo fare anche a meno del nome del comune, e linkare tutto per `comune_codice_istat`

Io sono d'accordo, modifico il file

**Comment by dennisangemi** [comment]
@gbvitrano tu saresti d'accordo a cancellare la folder `stemmi_nomi_comuni` per mantenere solo [questa](https://github.com/opendatasicilia/comuni-italiani/tree/main/img/stemmi_cod_istat)?

**Comment by pigreco** [comment]
ma non sarebbe meglio specificare (da qualche parte) che si tratta del codice `pro_com_t` ? ISTAT negli shapefile che mette a disposizione mette due codici: `pro_com` e `procom_t` rispettivmanete numerico e testuale.

ottimo lavoro

**Comment by gbvitrano** [comment]
Io li lascerei, possono tornare sempre utili, magari elimini la colonna dei
link nel csv.

Giovan Battista Vitrano - mobile - @gbvitrano

Il sab 25 set 2021, 12:58 Salvatore Fiandaca ***@***.***> ha
scritto:
