### ISSUE TITLE
codici postali mancanti

### ISSUE THREAD

**Issue by vince844** [opendatasicilia/comuni-italiani#20]
Grazie mille per questa repository. Ho notato che per alcuni comuni mancano alcuni codici postali per esempio per il comune di Catania è solo riportato il codice postale 95124 ma in realtà I CAP delle strade sono compresi tra 95121 e 95131

**Comment by gbvitrano** [comment]
Buongiorno, i CAP sono stati estratti da questo file [amministrazioni.txt](https://indicepa.gov.it/ipa-dati/dataset/amministrazioni) dataset [Agid-iPA](https://indicepa.gov.it/ipa-dati/organization/agid-ipa) che trovi  [Opendata IPA](https://indicepa.gov.it/ipa-dati/)
Nei vari dataset trovi solo il codice e non i poligoni dei cap.
Anche Palermo ha più cap da 90121 a 90151

Tutte le grandi città sono divise in più zone di cap. Ma i poligoni delle varie zone non sono opendata ma sono di proprietà di [Poste Italiane](https://business.poste.it/professionisti-imprese/prodotti/cap-zone-dati-integrabili-in-sistemi-geografici-gis.html).

**Comment by gbvitrano** [comment]
Codici catasto https://www1.agenziaentrate.gov.it/servizi/codici/ricerca/VisualizzaTabella.php?ArcName=COM-ICI

**Comment by gbvitrano** [comment]
Se vuoi puoi contribuire al repo :-)  scarica i nuovi dataset istat. Per aggiungere i codici catastali ti basta fare una semplice join 
[CODICI STATISTICI DELLE UNITÀ AMMINISTRATIVE TERRITORIALI: COMUNI, CITTÀ METROPOLITANE, PROVINCE E REGIONI](https://www.istat.it/it/archivio/6789)

![image](https://user-images.githubusercontent.com/20488693/172796514-fa23e2ce-3026-4805-88e0-8be5ffc037bc.png)

**Comment by gbvitrano** [comment]
Aggiunto ai dataset l'[elenco](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/comuni_codici-catastali.csv) con codice catastale. 

Basta fare una semplice join usando la colonna **pro_com_t**

![2022-06-09_13h09_38](https://user-images.githubusercontent.com/20488693/172833429-39ad1eb9-332e-45b0-ac08-011596bce90c.png)
