### ISSUE TITLE
comuni di Sassofeltrio e Montecopiolo

### ISSUE THREAD

**Issue by Paolikkio** [opendatasicilia/comuni-italiani#21]
in data 17/06/2021 i comuni in oggetto sono passati dalla provincia PU alla provincia RN
https://it.wikipedia.org/wiki/Sassofeltrio
https://it.wikipedia.org/wiki/Montecopiolo

**Comment by gbvitrano** [comment]
Tutto aggiornato, (salvo errori :-) ) sono cambiati i cod istat, il catastale, e i siti web, le email e CF sono rimaste le vecchie (verificate sul sito del comune
