### ISSUE TITLE
Specificare codice ISTAT

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/comuni-italiani#4]
ma non sarebbe meglio specificare (da qualche parte) che si tratta del codice `pro_com_t` ? ISTAT negli shapefile che mette a disposizione mette due codici: `pro_com` e `pro_com_t` rispettivmanete numerico e testuale.

ottimo lavoro

_Originally posted by @pigreco in https://github.com/opendatasicilia/comuni-italiani/issues/2#issuecomment-927104309_

**Comment by gbvitrano** [comment]
Non facciamo prima a rinominare la colonna `comune_codice_istat`  dei vari csv  direttamente in  `PRO_COM_T` così ci allineiamo alle tabelle istat?

**Comment by dennisangemi** [comment]
> Non facciamo prima a rinominare la colonna `comune_codice_istat` dei vari csv direttamente in `pro_com_t` così ci allineiamo alle tabelle istat?

Personalmente preferirei mantenere la dicitura `comune_codice_istat` semplicemente perchè secondo me consente una comprensione immediata. Io per primo non capivo cosa volesse dire `pro_com_t`.

**Comment by gbvitrano** [comment]
> > Non facciamo prima a rinominare la colonna `comune_codice_istat` dei vari csv direttamente in `pro_com_t` così ci allineiamo alle tabelle istat?
> 
> Personalmente preferirei mantenere la dicitura `comune_codice_istat` semplicemente perchè secondo me consente una comprensione immediata. Io per primo non capivo cosa volesse dire `pro_com_t`.

Allora metti una nota nel readme dei dati :-)

**Comment by dennisangemi** [comment]
> Allora metti una nota nel readme dei dati :-)

Fatto! Grazie. Chiudo ;)

**Comment by aborruso** [comment]
Ragazzi, non ho compreso moltissimo: ma non si può creare un README che descriva tutto e si lasciano i nomi dei campi per come sono?

**Comment by dennisangemi** [comment]
> Ragazzi, non ho compreso moltissimo: ma non si può creare un README che descriva tutto e si lasciano i nomi dei campi per come sono?

Eccolo [qui](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/README.md) Andrea. C'era già, ho solo aggiunto la precisazione ;)
