### ISSUE TITLE
proposta: indicare cosa rappresentano il file coordinate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/comuni-italiani#5]
il file [coordinate.csv](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/coordinate.csv) contiene i campi `lat` e `long`, propongo di scrivere:

- a cosa corrispondono: municipio comune, baricentro poligono delimitazione, ecc..;
-  inoltre indicherei encoding, separatore e sistema di riferimento delle coordinate (EPSG:4326)

**Comment by dennisangemi** [comment]
Taggo @gabacode che si è occupato del geocoding. https://github.com/opendatasicilia/informa-covid19/blob/main/script/dati-popolazione/1_latlong.py

**Comment by gabacode** [comment]
> * a cosa corrispondono: municipio comune, baricentro poligono delimitazione, ecc..;

Ciao @pigreco, non mi intendo molto di mappe ma credo che il centro non si riferisca al centro del poligono.

Ho fatto un esperimento con Palermo, che secondo le nostre coordinate `38.111227,13.352443`, si trova accanto al palazzo dei Normanni.
Calcolando il centro delle [boundaries](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=39513&class=boundary): `12.97760, 38.29856, 13.71643, 37.97668`

`Centro = (minY + maxY) / 2, (minX + maxX) / 2`
 = [38.13762, 13.347015](https://goo.gl/maps/NmFavg5rpefPLjaM7)

[OpenStreetMap](https://www.openstreetmap.org/node/67253662) lo chiama `admin_center`, ha senso?

> * inoltre indicherei encoding, separatore e sistema di riferimento delle coordinate (EPSG:4326)

Le coordinate sono calcolate via Python script, tramite [Nominatim](https://nominatim.openstreetmap.org/), che [sembra usare WSG84](https://wiki.openstreetmap.org/wiki/Converting_to_WGS84), si tratta quindi di [EPSG:4326](https://qastack.it/gis/3334/difference-between-wgs84-and-epsg4326)?

Inoltre, lo script ha arrotondato tutte le coordinate a 6 cifre, quindi hanno sforato di qualche metro rispetto al dato "originale" di OSM. Esempio di Palermo: `38.111227, 13.352443` vs `38.1112268,13.3524434`

Se può essere piu significativo, potremmo prendere i dati delle boundaries, ed eventualmente calcolare il centro fisico a partire da loro.

Dimmi tu, spero aiuti.

**Comment by pigreco** [comment]
ciao @gabacode ,

1. molto probabilmente sono le coordinate  riferite all'indirizzo della sede del municipio;
2. sì, si tratta di `EPSG:4326`;

se non erro, @aborruso in un suo [blog ](https://medium.com/tantotanto/cerco-un-centro-di-gravit%C3%A0-permanente-per-rappresentare-il-pendolarismo-tra-i-comuni-italiani-20198e33e493)su Medium parla dei centri abitati, ma in fondo all'articolo ci sono altri bei dati relativi ai municipi.
