### ISSUE TITLE
Adeguare file

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/comuni-italiani#7]
Adeguare [questo file](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/comuni_url_pec_cf.csv) (o comunque i nuovi file) secondo i criteri organizzativi di questo repo descritti nel readme

Aggiungere:

- [x] sito_web.csv
- [x] codice_fiscale.csv
- [x] cap.csv
- [x] pec.csv
- [x] wikipedia.csv

**Comment by dennisangemi** [comment]
@gbvitrano se sei d'accordo possiamo eliminare questo [file ](https://github.com/opendatasicilia/comuni-italiani/blob/main/dati/comuni_url_pec_cf.csv)perchè è stato adeguato agli "standard" di questo repo e aggiunto al main ;)

**Comment by gbvitrano** [comment]
fai pure :-)
