### ISSUE TITLE
proposta: inserire l'anno nel nome del campo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/comuni-italiani#9]
Nel file [popolazione _2021.csv](https://raw.githubusercontent.com/opendatasicilia/comuni-italiani/main/dati/popolazione_2021.csv) ci sono due campi `pro_com_t` e `popolazione`;

secondo la mia esperienza sarebbe utile inserire l'anno nel nome stesso per evitare che in futuro e facendo JOIN, si perda l'informazione sull'anno, vedi qui: 
![image](https://user-images.githubusercontent.com/7631137/134968279-d987e850-9f8e-4270-8147-0041817ce27e.png)

pertanto suggerirei:

1. `popRes21` o
2. `pop_res_21` o
3. `popMMXXI`

grazie

**Comment by dennisangemi** [comment]
utilizzerei la seconda proposta. Grazie @pigreco, tra un po' modifico.

**Comment by gbvitrano** [comment]
dobbiamo aggiungere colonne per gli altri anni

**Comment by dennisangemi** [comment]
Fatto! Se per voi va bene, chiudete pure ;)

**Comment by pigreco** [comment]
grazie @dennisangemi 

chiudo
